# Generated by Django 4.2.4 on 2023-08-31 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("instagram", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
                ),
                ("id", models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instagram",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="instagram.account"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
