# Generated by Django 4.2.5 on 2023-09-29 08:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dialogflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('igname', models.TextField()),
                ('thread_id', models.TextField(null=True)),
                ('booking_system', models.TextField()),
                ('calendar_availability', models.TextField()),
                ('social_media_activity', models.TextField()),
                ('ig_book_button', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstaMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('sent_by', models.TextField()),
                ('sent_on', models.DateTimeField()),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogflow.instalead')),
            ],
        ),
    ]
