# Generated by Django 4.2.2 on 2023-08-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dialogflow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scriptstage",
            name="abbreviation",
            field=models.CharField(default="N", max_length=3),
            preserve_default=False,
        ),
    ]
