# Generated by Django 4.2.5 on 2023-09-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogflow', '0002_instalead_instamessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalead',
            name='booking_system',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='instalead',
            name='calendar_availability',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='instalead',
            name='ig_book_button',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='instalead',
            name='social_media_activity',
            field=models.TextField(null=True),
        ),
    ]
