# Generated by Django 4.2.2 on 2023-08-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dialogflow", "0002_scriptstage_abbreviation"),
    ]

    operations = [
        migrations.AddField(
            model_name="scriptstage",
            name="level",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
