# Generated by Django 4.2.5 on 2023-09-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogflow', '0003_alter_instalead_booking_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalead',
            name='is_engaged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instalead',
            name='status',
            field=models.IntegerField(choices=[(1, 'Sending Compliment'), (2, 'Sending Needs Assessment Questions'), (3, 'Sending Solution To Problems'), (4, 'Resolving Objections')], default=1),
        ),
        migrations.AlterField(
            model_name='instalead',
            name='igname',
            field=models.TextField(unique=True),
        ),
    ]
