# Generated by Django 4.2.2 on 2023-08-30 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openai", "0002_delete_prompt"),
        ("dialogflow", "0003_scriptstage_level"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ScriptStage",
        ),
    ]
