# Generated by Django 4.2.5 on 2023-10-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogflow', '0004_instalead_is_engaged_instalead_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalead',
            name='status',
            field=models.IntegerField(choices=[(1, 'Sending Compliment'), (2, 'Sending Needs Assessment Questions'), (3, 'Sending Solution To Problems'), (4, 'Resolving Objections'), (5, 'Activating')], default=1),
        ),
    ]
