# Generated by Django 4.2.5 on 2023-10-19 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogflow', '0005_alter_instalead_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instamessage',
            name='lead_id',
        ),
        migrations.DeleteModel(
            name='InstaLead',
        ),
        migrations.DeleteModel(
            name='InstaMessage',
        ),
    ]
