name: Boosted Chat API CI

on:
  push:
    branches: [ action-test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
