# Generated by Django 4.2.4 on 2023-09-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_rep", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesrep",
            name="ig_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="salesrep",
            name="ig_username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
