# Generated by Django 4.2.2 on 2023-07-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
        ("sales_rep", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesrep",
            name="lead",
            field=models.ManyToManyField(to="leads.lead"),
        ),
    ]
