# Generated by Django 4.2.2 on 2023-07-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_rep", "0002_salesrep_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesrep",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
