# Generated by Django 4.2.4 on 2023-09-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0012_thread"),
        ("sales_rep", "0002_salesrep_ig_password_salesrep_ig_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesrep",
            name="instagram",
            field=models.ManyToManyField(blank=True, to="instagram.account"),
        ),
    ]
