# Generated by Django 4.2.2 on 2023-07-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0009_account_profile_url_alter_hashtag_name"),
        ("sales_rep", "0003_salesrep_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesrep",
            name="lead",
        ),
        migrations.AddField(
            model_name="salesrep",
            name="instagram",
            field=models.ManyToManyField(to="instagram.account"),
        ),
    ]
