# Generated by Django 4.2.8 on 2023-12-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rep', '0003_alter_salesrep_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrep',
            name='city',
            field=models.TextField(default='Pasadena'),
        ),
        migrations.AddField(
            model_name='salesrep',
            name='country',
            field=models.TextField(default='US'),
        ),
    ]
