# Generated by Django 5.0.6 on 2024-06-21 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rep', '0006_influencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadassignmenthistory',
            name='influencer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_rep.influencer'),
        ),
    ]
