# Generated by Django 4.2.7 on 2024-06-24 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rep', '0007_leadassignmenthistory_influencer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadassignmenthistory',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_rep.salesrep'),
        ),
    ]
