# Generated by Django 4.2.7 on 2024-07-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rep', '0008_alter_leadassignmenthistory_sales_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrep',
            name='android_release',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesrep',
            name='android_version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesrep',
            name='app_version',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='salesrep',
            name='cpu',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesrep',
            name='device',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='salesrep',
            name='dpi',
            field=models.CharField(blank=True, max_length=27, null=True),
        ),
        migrations.AddField(
            model_name='salesrep',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='salesrep',
            name='model',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='salesrep',
            name='resolution',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesrep',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'AVAILABLE'), (1, 'ACTIVE'), (2, 'CHALLLENGE REQUIRED')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='salesrep',
            name='version_code',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
