# Generated by Django 5.0.7 on 2024-07-24 13:00

import pgcrypto.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rep', '0009_salesrep_android_release_salesrep_android_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrep',
            name='ig_password',
            field=pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=255, null=True, verbose_name='ig_password'),
        ),
    ]
