# Generated by Django 5.1.3 on 2025-02-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rep', '0009_salesrep_android_release_salesrep_android_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrep',
            name='zip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
