# Generated by Django 5.0.7 on 2024-07-24 13:04

import pgcrypto.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rep', '0010_alter_salesrep_ig_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrep',
            name='ig_username',
            field=pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=255, null=True, verbose_name='ig_username'),
        ),
    ]
