# Generated by Django 4.2.2 on 2023-06-28 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scrapper", "0004_gmapsconfig_instagramconfig_styleseatconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
                ),
                ("id", models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gmaps",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="scrapper.gmapsconfig"
                    ),
                ),
                (
                    "instagram",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scrapper.instagramconfig",
                    ),
                ),
                (
                    "styleseat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scrapper.styleseatconfig",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
