# Generated by Django 4.2.2 on 2023-08-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationsheet",
            name="file",
            field=models.FileField(upload_to="media"),
        ),
    ]
