# Generated by Django 4.2.4 on 2023-09-09 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_rep", "0003_alter_salesrep_instagram"),
        ("settings", "0003_industry_remove_automationsheet_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationsheet",
            name="salesrep",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="sales_rep.salesrep"
            ),
        ),
    ]
