# Generated by Django 4.2.5 on 2023-10-24 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.TextField(default='ACTIVE'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('requested_on', models.DateTimeField(auto_now_add=True)),
                ('approved_rejected_on', models.DateTimeField(null=True)),
                ('rejection_reason', models.TextField(null=True)),
                ('approved_rejected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_approver', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_requestor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
