# Generated by Django 4.2.2 on 2023-06-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Links",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
                ),
                ("id", models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
