# Generated by Django 4.2.2 on 2023-06-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="links",
            name="source",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
