# Generated by Django 4.2.2 on 2023-06-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapper", "0002_links_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="links",
            name="source",
            field=models.CharField(choices=[(1, "Google"), (2, "StyleSeat")], default=1, max_length=9),
        ),
    ]
