# Generated by Django 4.2.2 on 2023-06-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapper", "0003_alter_links_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="GmapsConfig",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
                ),
                ("id", models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("specific_element", models.CharField(blank=True, max_length=255, null=True)),
                ("css_selector_search_box", models.CharField(blank=True, max_length=255, null=True)),
                ("area_of_search", models.CharField(blank=True, max_length=50, null=True)),
                ("search_button", models.CharField(blank=True, max_length=255, null=True)),
                ("delay", models.IntegerField(blank=True, null=True)),
                ("xpath_business", models.CharField(blank=True, max_length=255, null=True)),
                ("xpath_review", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InstagramConfig",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
                ),
                ("id", models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("xpath_search", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StyleSeatConfig",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
                ),
                ("id", models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("css_selector_service_box", models.CharField(blank=True, max_length=255, null=True)),
                ("css_selector_area_box", models.CharField(blank=True, max_length=255, null=True)),
                ("css_selector_submit_btn", models.CharField(blank=True, max_length=255, null=True)),
                ("css_selector_seats", models.CharField(blank=True, max_length=255, null=True)),
                ("xpath_name", models.CharField(blank=True, max_length=255, null=True)),
                ("xpath_popup", models.CharField(blank=True, max_length=255, null=True)),
                ("service", models.CharField(blank=True, max_length=255, null=True)),
                ("area", models.CharField(blank=True, max_length=255, null=True)),
                ("delay", models.IntegerField(blank=True, null=True)),
                ("xpath_ig_username", models.CharField(blank=True, max_length=255, null=True)),
                ("xpath_review", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
