# Generated by Django 4.2.2 on 2023-06-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrapper", "0004_gmapsconfig_instagramconfig_styleseatconfig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gmapsconfig",
            name="area_of_search",
        ),
        migrations.RemoveField(
            model_name="styleseatconfig",
            name="area",
        ),
        migrations.RemoveField(
            model_name="styleseatconfig",
            name="service",
        ),
    ]
