from django.urls import path

from . import views

urlpatterns = [
    path("fallbackWebhook/", views.FallbackWebhook.as_view()),
    path("needsAssessmentWebhook/", views.NeedsAssesmentWebhook.as_view()),
    path('create-lead/',
         views.create_lead,
         name='create_lead'),
    path('delete-lead/',
         views.delete_lead,
         name='delete_lead'),
    path('create-lead-send-compliment/',
         views.create_lead_and_send_compliment,
         name='create_lead_and_send_compliment'),
    path('start-lead-engagement/<leadId>/',
         views.start_lead_engagement,
         name='start_lead_engagement'),
    path('get-leads/',
         views.get_leads,
         name='get_leads'),
    path('update-lead/<leadId>/',
         views.update_lead,
         name='update_lead'),
    path('simulate-check-message/',
         views.simulate_check_message,
         name='simulate_check_message'),
    path('delete-message/<pk>/',
         views.delete_message,
         name='delete_message'),
    path('get-messages/',
         views.get_messages,
         name='get_messages'),
    path('get-messages-by-lead/<leadId>/',
         views.get_messages_by_lead,
         name='get_messages_by_lead'),
    path('set-check-message-periodic-task/',
         views.set_check_message_periodic_task,
         name='set_check_message_periodic_task'),
    path('update-check-message-periodic-task/',
         views.update_check_message_periodic_task,
         name='update_check_message_periodic_task')
]
