# Generated by Django 4.2.4 on 2023-09-01 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutSourcedData",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
                ),
                ("id", models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("results", models.JSONField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="account",
            name="competitor",
        ),
        migrations.RemoveField(
            model_name="account",
            name="gmaps_business_name",
        ),
        migrations.RemoveField(
            model_name="account",
            name="is_from_styleseat",
        ),
        migrations.RemoveField(
            model_name="account",
            name="review",
        ),
        migrations.AddField(
            model_name="account",
            name="outsourced",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="instagram.outsourceddata"
            ),
        ),
    ]
