# Generated by Django 4.2.4 on 2023-09-01 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0002_outsourceddata_remove_account_competitor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutSourced",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(blank=True, max_length=256, null=True)),
                ("results", models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name="account",
            name="outsourced",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="instagram.outsourced"
            ),
        ),
        migrations.DeleteModel(
            name="OutSourcedData",
        ),
    ]
