# Generated by Django 4.2.4 on 2023-09-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0003_outsourced_alter_account_outsourced_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outsourced",
            name="source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
