# Generated by Django 4.2.4 on 2023-09-01 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0004_alter_outsourced_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutSourcedInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("results", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="account",
            name="outsourced",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="instagram.outsourcedinfo"
            ),
        ),
    ]
