# Generated by Django 4.2.2 on 2023-06-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0004_account_is_from_styleseat_account_styleseat_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="igname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
