# Generated by Django 4.2.4 on 2023-09-04 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0005_outsourcedinfo_alter_account_outsourced"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="photo",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="instagram.photo"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="reel",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="instagram.reel"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="story",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="instagram.story"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="video",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="instagram.video"
            ),
        ),
    ]
