# Generated by Django 4.2.2 on 2023-06-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0005_alter_account_igname"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="gmaps_business_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
