# Generated by Django 4.2.4 on 2023-09-04 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0006_account_photo_account_reel_account_story_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="account",
            name="reel",
        ),
        migrations.RemoveField(
            model_name="account",
            name="story",
        ),
        migrations.RemoveField(
            model_name="account",
            name="video",
        ),
    ]
