# Generated by Django 4.2.2 on 2023-06-26 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0006_account_gmaps_business_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="styleseat_review",
            new_name="review",
        ),
    ]
