# Generated by Django 4.2.2 on 2023-06-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0007_rename_styleseat_review_account_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="hashtag",
            name="name",
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
