# Generated by Django 4.2.2 on 2023-06-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0008_hashtag_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="profile_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hashtag",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
