# Generated by Django 4.2.2 on 2023-08-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0009_account_profile_url_alter_hashtag_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="competitor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
