# Generated by Django 4.2.4 on 2023-09-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0010_statuscheck_account_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="stage",
        ),
        migrations.AddField(
            model_name="statuscheck",
            name="stage",
            field=models.IntegerField(
                choices=[(1, "Oven"), (2, "Needs Assessment"), (3, "Overcoming Objections"), (4, "Activation")],
                default=1,
            ),
        ),
    ]
