# Generated by Django 4.2.4 on 2023-09-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0013_thread_replied_thread_replied_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="replied",
            field=models.BooleanField(default=False),
        ),
    ]
