# Generated by Django 4.2.4 on 2023-09-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0014_alter_thread_replied"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="replied",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
