# Generated by Django 4.2.4 on 2023-09-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0018_outsourcedinfo_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="dormant_profile_created",
            field=models.BooleanField(default=True),
        ),
    ]
