# Generated by Django 4.2.4 on 2023-09-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0019_account_dormant_profile_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="dormant_profile_created",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
