# Generated by Django 4.2.4 on 2023-09-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0020_alter_account_dormant_profile_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="content",
            field=models.TextField(blank=True, default="test", null=True),
        ),
    ]
