# Generated by Django 4.2.4 on 2023-10-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0021_thread_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="robot_response",
            field=models.TextField(blank=True, default="test", null=True),
        ),
    ]
