# Generated by Django 4.2.4 on 2023-10-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0022_thread_robot_response"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
                ),
                ("id", models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(blank=True, default="test", null=True)),
                ("robot_response", models.TextField(blank=True, default="test", null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="thread",
            name="content",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="robot_response",
        ),
        migrations.AddField(
            model_name="thread",
            name="message",
            field=models.ManyToManyField(blank=True, to="instagram.message"),
        ),
    ]
