# Generated by Django 4.2.4 on 2023-10-01 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0023_message_remove_thread_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thread",
            name="message",
        ),
        migrations.AddField(
            model_name="message",
            name="message",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="instagram.thread"
            ),
        ),
    ]
