# Generated by Django 4.2.4 on 2023-10-01 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0024_remove_thread_message_message_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="message",
            new_name="thread",
        ),
    ]
