# Generated by Django 4.2.4 on 2023-10-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0025_rename_message_message_thread"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="robot_response",
        ),
        migrations.AddField(
            model_name="message",
            name="sent_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
