# Generated by Django 4.2.5 on 2023-10-01 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0026_remove_message_robot_response_message_sent_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 8, 31, 27, 669088, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
