# Generated by Django 4.2.4 on 2023-10-01 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0027_alter_account_outsourced"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="outsourced",
        ),
        migrations.AddField(
            model_name="outsourced",
            name="account",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="instagram.account"
            ),
        ),
    ]
