# Generated by Django 4.2.5 on 2023-10-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0027_message_sent_on'),
        ('instagram', '0028_remove_account_outsourced_outsourced_account'),
    ]

    operations = [
    ]
