# Generated by Django 4.2.5 on 2023-10-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0030_account_confirmed_problems_account_rejected_problems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='igname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
