# Generated by Django 4.2.7 on 2023-11-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0033_account_full_name_account_qualified'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
