# Generated by Django 4.2.7 on 2023-12-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0035_account_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='replied',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='replied_at',
        ),
        migrations.AddField(
            model_name='thread',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='last_message_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='unread_message_count',
            field=models.IntegerField(default=0),
        ),
    ]
