# Generated by Django 4.2.8 on 2024-01-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0036_remove_thread_replied_remove_thread_replied_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='index',
            field=models.IntegerField(default=1),
        ),
    ]
