# Generated by Django 4.2.7 on 2024-01-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0037_alter_account_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='qualified_keywords',
            field=models.TextField(blank=True, default='test', null=True),
        ),
    ]
