# Generated by Django 4.2.7 on 2024-01-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0038_account_qualified_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='linked_to',
            field=models.CharField(blank=True, default='no_one', max_length=255, null=True),
        ),
    ]
