# Generated by Django 4.2.7 on 2024-01-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0039_account_linked_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='qualified_keywords',
        ),
    ]
