# Generated by Django 4.2.7 on 2024-02-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0041_account_referral_account_status_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='referral',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
