# Generated by Django 4.2.7 on 2024-03-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0042_alter_account_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='script_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='script_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
