# Generated by Django 4.2.7 on 2024-07-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0043_account_script_score_account_script_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='solution_presented',
            field=models.BooleanField(default=False),
        ),
    ]
