# Generated by Django 4.2.7 on 2024-07-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0044_account_solution_presented'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='question_asked',
            field=models.BooleanField(default=False),
        ),
    ]
