# Generated by Django 4.2.7 on 2024-07-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0045_account_question_asked'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='relevant_information',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='scraped',
            field=models.BooleanField(default=False),
        ),
    ]
