# Generated by Django 4.2.7 on 2024-07-29 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0046_account_relevant_information_account_scraped'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachTime',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_slot', models.DateTimeField()),
                ('account_to_be_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
