# Generated by Django 5.0.7 on 2024-11-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0049_accountsclosed'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='content_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='content_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
