# Generated by Django 5.0.7 on 2024-11-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0050_message_content_data_message_content_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
