# Generated by Django 5.0.7 on 2024-12-04 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0050_unwantedaccount'),
        ('instagram', '0051_message_message_id'),
    ]

    operations = [
    ]
