# Generated by Django 5.0.7 on 2024-12-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0052_merge_0050_unwantedaccount_0051_message_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unwantedaccount',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=False),
        ),
    ]
