# Generated by Django 5.0.7 on 2024-12-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0053_alter_unwantedaccount_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
