# Generated by Django 4.2.7 on 2025-01-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0055_remove_comment_text_comment_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='optionalAvatarUrl',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='optionalAvatarUrl',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
