# Generated by Django 4.2.7 on 2025-01-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0056_alter_comment_optionalavatarurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='outreach_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='outreach_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
