# Generated by Django 4.2.7 on 2025-01-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0057_account_outreach_success_account_outreach_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='outreach_time',
            field=models.DateTimeField(),
        ),
    ]
