# Generated by Django 4.2.11 on 2024-04-15 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales_rep', '0004_salesrep_city_salesrep_country'),
        ('instagram', '0043_account_script_score_account_script_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('error_message', models.TextField()),
                ('error_type', models.TextField()),
                ('log_level', models.CharField(choices=[('WARNING', 'Warning'), ('ERROR', 'Error')], default='ERROR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.account')),
                ('sales_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_rep.salesrep')),
            ],
        ),
    ]
