name: Django CI

on:
  push:
    # branches: [ action-test ]
    branches: [ "*" ]
  # pull_request:
  #   branches: [ "*" ]
  #   types: [opened, closed, reopened]

env:
  CELERY_BROKER_URL_API: $CELERY_BROKER_URL_API
  CELERY_RESULT_BACKEND_API: $CELERY_RESULT_BACKEND_API
  MAILCHIMP_API_KEY: $MAILCHIMP_API_KEY
  MAILCHIMP_DATA_CENTER: $MAILCHIMP_DATA_CENTER
  MAILCHIMP_EMAIL_LIST_ID: $MAILCHIMP_EMAIL_LIST_ID
  EMAIL_HOST_USER: $EMAIL_HOST_USER
  EMAIL_HOST_PASSWORD: $EMAIL_HOST_PASSWORD
  IG_USERNAME: ${{SECRETS.IG_USERNAME}}
  IG_PASSWORD: ${{SECRETS.IG_PASSWORD}}
  CHALLENGE_EMAIL: ${{SECRETS.CHALLENGE_EMAIL}}
  CHALLENGE_PASSWORD: ${{SECRETS.CHALLENGE_PASSWORD}}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # - name: Run Tests
    #   run: |
    #     python manage.py test



    - name: Login To Docker Hub
      uses: docker/login-action@v3 # mr-smithers-excellent/docker-build-push@v4 # use existing coker action
      with:
        context: .
        push: true
        tags: lunyamwimages/boostedchat-api-dev:latest
        # registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: lunyamwimages/boostedchatapi-dev:latest


    # - name: Create a comment
    #   uses: Asana/comment-on-task-github-action@v1.2
    #   id: createComment
    #   with:
    #     asana-secret: ${{ secrets.ASANA_SECRET }}
    #     comment-text: "{{PR_NAME}} is {{PR_STATE}}: {{PR_URL}}"
    # - name: Get status
    #   run: echo "Status is ${{ steps.createComment.outputs.status }}"
